-- 001_init.sql
-- RFID Middleware initial schema migration
-- Created on 2025-10-28 12:15:00

CREATE TABLE IF NOT EXISTS tags (
  epc VARCHAR(128) PRIMARY KEY,
  sku VARCHAR(100),
  brand VARCHAR(100),
  sale_status VARCHAR(32) DEFAULT 'AVAILABLE',
  reserved_txn VARCHAR(128) NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS tag_events (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  epc VARCHAR(128) NOT NULL,
  event_type VARCHAR(64),
  source VARCHAR(64),
  data JSON,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  INDEX (epc),
  INDEX (event_type)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS pos_transactions (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  pos_txn_id VARCHAR(128) NOT NULL UNIQUE,
  store_id VARCHAR(128),
  user_id VARCHAR(128),
  items JSON,
  total_amount DECIMAL(12,2),
  status VARCHAR(32),
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
